name: 'Daily Job'

on:
  schedule:
    - cron: '0 1 * * *'  # 每天UTC时间01:00运行
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'

jobs:
  run_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up committer identity
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        
    - name: Pull latest code from upstream repository
      run: |
        git remote add upstream https://github.com/kimwang1978/collect-tv-txt.git || true
        git fetch upstream
        git checkout main
        # 尝试合并上游项目的最新更改
        git merge upstream/main --allow-unrelated-histories || true

    # 检查合并冲突并解决，保留本地分支的 .github/workflows/main.yml 和 README.md
    # - name: Resolve merge conflicts for main.yml and README.md
    #   run: |
    #     conflict_files=$(git ls-files -u | awk '{print $4}' | sort -u)
    #     if [[ "$conflict_files" == *".github/workflows/main.yml"* ]] || [[ "$conflict_files" == *"README.md"* ]]; then
    #       echo "Merge conflict detected in .github/workflows/main.yml or README.md, keeping current branch version"
          
    #       # 保留本地分支的 .github/workflows/main.yml 和 README.md 文件
    #       git checkout --ours .github/workflows/main.yml
    #       git checkout --ours README.md
          
    #       # 标记这些文件为已解决
    #       git add .github/workflows/main.yml
    #       git add README.md
    #     fi

    # 处理所有其他未解决的冲突文件，保留本地分支的版本
    - name: Resolve remaining conflicts by keeping local changes
      run: |
        remaining_conflicts=$(git ls-files -u | awk '{print $4}' | sort -u)
        if [[ -n "$remaining_conflicts" ]]; then
          echo "Resolving remaining conflicts by keeping local branch versions"
          for file in $remaining_conflicts; do
            git checkout --ours "$file"
            git add "$file"
          done
        fi


    - name: Modify main.py to set about and about_video1 to empty strings
      run: |
        sed -i 's/about=.*/about=""/' main.py
        sed -i 's/about_video1=.*/about_video1=""/' main.py
        sed -i 's/about_video2=.*/about_video2=""/' main.py

    - name: Run Python script
      run: python main.py
      
    - name: Upload generated files
      uses: actions/upload-artifact@v4
      with:
        name: generated-files
        path: |
          merged_output.txt
          others_output.txt
          
    - name: 提交更改
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add merged_output.txt
        git add merged_output.m3u
        git add merged_output_simple.txt
        git add merged_output_simple.m3u
        git add others_output.txt
        git commit -m ":tada: AutoUpdate $(date +'%Y%m%d')"
        
        current_datetime=$(date +"%Y%m%d_%H%M%S")
        cp merged_output.txt history/"${current_datetime}_merged_output.txt"
        cp others_output.txt history/"${current_datetime}_others_output.txt"
        git add history/"${current_datetime}_merged_output.txt"
        git add history/"${current_datetime}_others_output.txt"
        git commit -m "Archive file with timestamp"
          
    - name: Push changes to my forked repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
